name: CMake Build

on:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run:  |
        cmake . -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        mingw32-make
        mkdir artifact && move maniac.exe artifact/maniac-win64.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build-windows-latest
        path: artifact
